spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/okdol?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: okdol
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    open-in-view: false
