# This is a basic workflow to help you get started with Actions
name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ master ]

env:
  PROJECT_NAME: cicd_project
  BUCKET_NAME: cicd-okdol
  CODE_DEPLOY_APP_NAME: cicd
  DEPLOYMENT_GROUP_NAME: cicd

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 브랜치로 이동
        uses: actions/checkout@v3
        
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          
      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash
      
      - name: 프로젝트 빌드
        run: ./gradlew build
        shell: bash
        
      - name: Zip File 생성
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
      
      - name: AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: S3에 업로드
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: EC2에 배포
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
